version: "3"
services:
  postgres:
    build: ./app
  symfony:
    image: ${DOCKER_REGISTRY-}symfony:${SYMFONY_VERSION:-latest}
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
  frontend:
    image : react:latest
    ports:
      - "3010:3000"